FROM raspbian/stretch:latest

# Copy dependent files (instead of mount to support Windows)
COPY . /drone

# Install dependenies
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
    git \
    bzip2 \
    libz-dev \
    libi2c-dev \
    build-essential

# Install pre-complied GCC 9.1 (https://bitbucket.org/sol_prog/raspberry-pi-gcc-binary/src/master/)
RUN git clone https://bitbucket.org/sol_prog/raspberry-pi-gcc-binary.git
RUN cd /raspberry-pi-gcc-binary && tar -xjvf gcc-9.1.0-armhf-raspbian.tar.bz2
RUN mv /raspberry-pi-gcc-binary/gcc-9.1.0 /opt
RUN rm -r /raspberry-pi-gcc-binary
ENV PATH /opt/gcc-9.1.0/bin:$PATH
ENV LD_LIBRARY_PATH /opt/gcc-9.1.0/lib:$LD_LIBRARY_PATH
RUN ln -s /usr/include/arm-linux-gnueabihf/sys /usr/include/sys
RUN ln -s /usr/include/arm-linux-gnueabihf/bits /usr/include/bits
RUN ln -s /usr/include/arm-linux-gnueabihf/gnu /usr/include/gnu
RUN ln -s /usr/include/arm-linux-gnueabihf/asm /usr/include/asm
RUN ln -s /usr/lib/arm-linux-gnueabihf/crti.o /usr/lib/crti.o
RUN ln -s /usr/lib/arm-linux-gnueabihf/crt1.o /usr/lib/crt1.o
RUN ln -s /usr/lib/arm-linux-gnueabihf/crtn.o /usr/lib/crtn.o
