FROM gcc:9.1

# Create symbolic links ("alias") for GCC 9.1
RUN cd /bin && ln -s /usr/local/bin/gcc gcc-9.1
RUN cd /bin && ln -s /usr/local/bin/g++ g++-9.1

# Copy dependent files (instead of mount to support Windows)
ENV ROOT /raspi
WORKDIR ${ROOT}
COPY . ${ROOT}

# Make entry shell script executable
RUN chmod +x ./run_tests.sh
