
name: ci
on: [push]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Setup qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm/v7
      -
        name: Build documentation
        run: make -C ./doc
      -
        name: Install tools & unit test
        run: make -C ./tools
      -
        name: Compile (host) raspi & unit test
        run: make -C ./raspi -f Makefile_tests
      -
        name: Compile (target) raspi & build dpkg
        run: make -C ./raspi -f Makefile_dpkg
